version: "2.2"
services:
    bird:
        image: quay.io/iwarp/bird:latest
        build: .
        network_mode: host
        tty: true
        volumes:
        - /etc/bird:/etc/bird:ro
        - /run/bird:/run/bird:rw
